services:
    mongodb:
        image: mongo:latest
        container_name: mongo_container
        restart: always
        environment:
            MONGO_INITDB_DATABASE: movies
        ports:
            - 27017:27017
        volumes:
          - ./mongo/mongorestore.sh:/docker-entrypoint-initdb.d/mongorestore.sh
          - ./mongo:/mongo_restore
        networks:
            - practica_final
networks:
    practica_final:
        driver: bridge