services:
    mongodb:
        image: mongo:latest
        container_name: mongo_container
        restart: always
        environment:
            - MONGO_INITDB_DATABASE=${MONGODB_INITDB_DATABASE}
        ports:
            - "27017:27017"
        volumes:
          - ./mongo/mongorestore.sh:/docker-entrypoint-initdb.d/mongorestore.sh
          - ./mongo:/mongo_restore
        networks:
            - practica_net
    backend:
        build:
            context: ./backend
            dockerfile: Dockerfile
        container_name: backend_container
        command: npm start
        ports:
            - "4000:4000"
        depends_on:
            - mongodb
        networks:
            - practica_net
    frontend:
        build:
            context: ./frontend
            dockerfile: Dockerfile
        container_name: frontend_container
        command: npm start
        ports:
            - "3000:3000"
        depends_on:
            - backend
        networks:
            - practica_net
    mongo-express:
        image: mongo-express
        container_name: adminMongo_container
        ports:
            - "8081:8081"
        environment:
            - ME_CONFIG_MONGODB_SERVER=${DB_HOST}
            - ME_CONFIG_MONGODB_URL=${ME_CONFIG_MONGODB_URL}
        depends_on:
            - mongodb
        networks:
            - practica_net
    nginx-loadbalancer:
        image: nginx:latest
        container_name: nginx-loadbalancer_container
        ports: 
            - "80:80"
        volumes:
            - ./loadbalancer/nginx.conf:/etc/nginx/nginx.conf
        command: nginx -g "daemon off;"
        depends_on:
            - frontend
        networks:
            - practica_net
    prometheus:
        image: prom/prometheus:v2.20.1
        container_name: prometheus_practica
        volumes:
            - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
        command: --config.file=/etc/prometheus/prometheus.yml
        ports:
            - "9090:9090"
        networks:
            - practica_net
    grafana:
        image: grafana/grafana:7.1.5
        container_name: grafana_practica
        volumes:
            - ./myGrafanaVol:/var/lib/grafana
            - ./grafana/datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml
        environment:
            - GF_AUTH_BASIC_ENABLED=${GF_AUTH_BASIC_ENABLED}
            - GF_AUTH_ANONYMOUS_ENABLED=${GF_AUTH_ANONYMOUS_ENABLED}
            - GF_AUTH_ANONYMOUS_ORG_ROLE=${GF_AUTH_ANONYMOUS_ORG_ROLE}
            - GF_INSTALL_PLUGINS=${GF_INSTALL_PLUGINS}
        depends_on:
            - prometheus
        ports:
            - "3500:3000"
        networks:
            - practica_net
networks:
    practica_net:
        driver: bridge