services:
    mongodb:
        image: mongo:latest
        container_name: mongo_container
        restart: always
        environment:
            - MONGO_INITDB_DATABASE=${MONGODB_INITDB_DATABASE}
        ports:
            - "27017:27017"
        volumes:
          - ./mongo/mongorestore.sh:/docker-entrypoint-initdb.d/mongorestore.sh
          - ./mongo:/mongo_restore
        networks:
            - practica_net
    backend:
        build:
            context: ./backend
            dockerfile: Dockerfile
        container_name: backend_container
        command: npm start
        ports:
            - "4000:4000"
        depends_on:
            - mongodb
        networks:
            - practica_net
    frontend:
        build:
            context: ./frontend
            dockerfile: Dockerfile
        container_name: frontend_container
        command: npm start
        ports:
            - "3000:3000"
        depends_on:
            - backend
        networks:
            - practica_net
    mongo-express:
        image: mongo-express
        container_name: adminMongo_container
        ports:
            - "8081:8081"
        environment:
            - ME_CONFIG_MONGODB_SERVER=${DB_HOST}
            - ME_CONFIG_MONGODB_URL=${ME_CONFIG_MONGODB_URL}
        depends_on:
            - mongodb
        networks:
            - practica_net
networks:
    practica_net:
        driver: bridge